version: '3'

services:
  bot:
    image: ghcr.io/hacksquaddev/discord-rust:main@sha256:e94722f996db616e724bdd08865638e2649b432ee16b09b181ab9615ccb001ae
    # build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - REDIS_URI=redis://redis/

  redis:
    image: redis:latest
